package eu.europa.ec.fisheries.ers.fa.entities;

// Generated 06-May-2016 14:29:53 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ActivityAppStock generated by hbm2java
 */
@Entity
@Table(name = "activity_app_stock", schema = "activity")
public class AppStock implements java.io.Serializable {

	
	@Id
	@Column(name = "id", unique = true, nullable = false)
	private int id;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "fa_catch_id")
	private FaCatch faCatch;
	
	@Column(name = "stock_id")
	private String stockId;
	
	@Column(name = "stock_scheme_id")
	private String stockSchemeId;

	public AppStock() {
	}

	public AppStock(int id) {
		this.id = id;
	}

	public AppStock(int id, FaCatch faCatch,
			String stockId, String stockSchemeId) {
		this.id = id;
		this.faCatch = faCatch;
		this.stockId = stockId;
		this.stockSchemeId = stockSchemeId;
	}

	
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	
	public FaCatch getFaCatch() {
		return this.faCatch;
	}

	public void setFaCatch(FaCatch faCatch) {
		this.faCatch = faCatch;
	}

	
	public String getStockId() {
		return this.stockId;
	}

	public void setStockId(String stockId) {
		this.stockId = stockId;
	}

	
	public String getStockSchemeId() {
		return this.stockSchemeId;
	}

	public void setStockSchemeId(String stockSchemeId) {
		this.stockSchemeId = stockSchemeId;
	}

}
