package eu.europa.ec.fisheries.ers.fa.entities;

// Generated 06-May-2016 14:29:53 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * ActivityContactParty generated by hbm2java
 */
@Entity
@Table(name = "activity_contact_party", schema = "activity", uniqueConstraints = @UniqueConstraint(columnNames = "contact_person_id"))
public class ContactParty implements java.io.Serializable {

	
	@Id
	@Column(name = "id", unique = true, nullable = false)
	private int id;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "contact_person_id", unique = true, nullable = false)
	private ContactPerson contactPerson;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "vessel_transport_means_id")
	private VesselTransportMeans vesselTransportMeans;
	
	@Column(name = "role_code", nullable = false)
	private String roleCode;
	
	@Column(name = "role_code_list_id", nullable = false)
	private String roleCodeListId;
	

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "contactParty")
	private Set<StructuredAddress> structuredAddresses = new HashSet<StructuredAddress>(
			0);

	public ContactParty() {
	}

	public ContactParty(int id,
			ContactPerson contactPerson, String roleCode,
			String roleCodeListId) {
		this.id = id;
		this.contactPerson = contactPerson;
		this.roleCode = roleCode;
		this.roleCodeListId = roleCodeListId;
	}

	public ContactParty(int id,
			ContactPerson contactPerson,
			VesselTransportMeans vesselTransportMeans,
			String roleCode, String roleCodeListId,
			Set<StructuredAddress> structuredAddresses) {
		this.id = id;
		this.contactPerson = contactPerson;
		this.vesselTransportMeans = vesselTransportMeans;
		this.roleCode = roleCode;
		this.roleCodeListId = roleCodeListId;
		this.structuredAddresses = structuredAddresses;
	}

	
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	
	public ContactPerson getContactPerson() {
		return this.contactPerson;
	}

	public void setContactPerson(
			ContactPerson contactPerson) {
		this.contactPerson = contactPerson;
	}


	public VesselTransportMeans getVesselTransportMeans() {
		return this.vesselTransportMeans;
	}

	public void setVesselTransportMeans(
			VesselTransportMeans vesselTransportMeans) {
		this.vesselTransportMeans = vesselTransportMeans;
	}

	
	public String getRoleCode() {
		return this.roleCode;
	}

	public void setRoleCode(String roleCode) {
		this.roleCode = roleCode;
	}


	public String getRoleCodeListId() {
		return this.roleCodeListId;
	}

	public void setRoleCodeListId(String roleCodeListId) {
		this.roleCodeListId = roleCodeListId;
	}

	public Set<StructuredAddress> getStructuredAddresses() {
		return this.structuredAddresses;
	}

	public void setStructuredAddresses(
			Set<StructuredAddress> structuredAddresses) {
		this.structuredAddresses = structuredAddresses;
	}

}
