package eu.europa.ec.fisheries.ers.fa.entities;

// Generated 06-May-2016 14:29:53 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ActivityDelimitedPeriod generated by hbm2java
 */
@Entity
@Table(name = "activity_delimited_period", schema = "activity")
public class DelimitedPeriod implements java.io.Serializable {

	
	@Id
	@Column(name = "id", unique = true, nullable = false)
	private int id;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "fishing_activity_id")
	private FishingActivity fishingActivity;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "fishing_trip_id")
	private FishingTrip fishingTrip;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "start_date", length = 29)
	private Date startDate;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "end_date", length = 29)
	private Date endDate;
	
	@Column(name = "duration")
	private String duration;

	public DelimitedPeriod() {
	}

	public DelimitedPeriod(int id) {
		this.id = id;
	}

	public DelimitedPeriod(int id,
			FishingActivity fishingActivity,
			FishingTrip fishingTrip, Date startDate,
			Date endDate, String duration) {
		this.id = id;
		this.fishingActivity = fishingActivity;
		this.fishingTrip = fishingTrip;
		this.startDate = startDate;
		this.endDate = endDate;
		this.duration = duration;
	}

	
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	
	public FishingActivity getFishingActivity() {
		return this.fishingActivity;
	}

	public void setFishingActivity(
			FishingActivity fishingActivity) {
		this.fishingActivity = fishingActivity;
	}

	
	public FishingTrip getFishingTrip() {
		return this.fishingTrip;
	}

	public void setFishingTrip(FishingTrip fishingTrip) {
		this.fishingTrip = fishingTrip;
	}

	
	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	
	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	
	public String getDuration() {
		return this.duration;
	}

	public void setDuration(String duration) {
		this.duration = duration;
	}

}
