package eu.europa.ec.fisheries.ers.fa.entities;

// Generated 06-May-2016 14:29:53 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * ActivityFaCatch generated by hbm2java
 */
@Entity
@Table(name = "activity_fa_catch", schema = "activity", uniqueConstraints = @UniqueConstraint(columnNames = "size_distribution_id"))
public class FaCatch implements java.io.Serializable {

	private int id;
	private FishingActivity fishingActivity;
	private SizeDistribution sizeDistribution;
	private String typeCode;
	private String typeCodeListId;
	private String speciesCode;
	private String speciesCodeListid;
	private Long unitQuantity;
	private Double weightMeasure;
	private String weightMeasureUnitCode;
	private String weightMeasureListId;
	private String usageCode;
	private String usageCodeListId;
	private String weighingMeansCode;
	private String weighingMeansCodeListId;
	private String aapStockType;
	private Set<AapProcess> aapProcesses = new HashSet<AapProcess>(
			0);
	private Set<FishingGear> fishingGears = new HashSet<FishingGear>(
			0);
	private Set<FluxLocation> fluxLocations = new HashSet<FluxLocation>(
			0);
	private Set<FluxCharacteristic> fluxCharacteristics = new HashSet<FluxCharacteristic>(
			0);
	private Set<AppStock> appStocks = new HashSet<AppStock>(
			0);
	private Set<FishingTrip> fishingTrips = new HashSet<FishingTrip>(
			0);

	public FaCatch() {
	}

	public FaCatch(int id,
			SizeDistribution sizeDistribution, String typeCode,
			String typeCodeListId, String speciesCode, String speciesCodeListid) {
		this.id = id;
		this.sizeDistribution = sizeDistribution;
		this.typeCode = typeCode;
		this.typeCodeListId = typeCodeListId;
		this.speciesCode = speciesCode;
		this.speciesCodeListid = speciesCodeListid;
	}

	public FaCatch(int id,
			FishingActivity fishingActivity,
			SizeDistribution sizeDistribution, String typeCode,
			String typeCodeListId, String speciesCode,
			String speciesCodeListid, Long unitQuantity, Double weightMeasure,
			String weightMeasureUnitCode, String weightMeasureListId,
			String usageCode, String usageCodeListId, String weighingMeansCode,
			String weighingMeansCodeListId, String aapStockType,
			Set<AapProcess> aapProcesses,
			Set<FishingGear> fishingGears,
			Set<FluxLocation> fluxLocations,
			Set<FluxCharacteristic> fluxCharacteristics,
			Set<AppStock> appStocks,
			Set<FishingTrip> fishingTrips) {
		this.id = id;
		this.fishingActivity = fishingActivity;
		this.sizeDistribution = sizeDistribution;
		this.typeCode = typeCode;
		this.typeCodeListId = typeCodeListId;
		this.speciesCode = speciesCode;
		this.speciesCodeListid = speciesCodeListid;
		this.unitQuantity = unitQuantity;
		this.weightMeasure = weightMeasure;
		this.weightMeasureUnitCode = weightMeasureUnitCode;
		this.weightMeasureListId = weightMeasureListId;
		this.usageCode = usageCode;
		this.usageCodeListId = usageCodeListId;
		this.weighingMeansCode = weighingMeansCode;
		this.weighingMeansCodeListId = weighingMeansCodeListId;
		this.aapStockType = aapStockType;
		this.aapProcesses = aapProcesses;
		this.fishingGears = fishingGears;
		this.fluxLocations = fluxLocations;
		this.fluxCharacteristics = fluxCharacteristics;
		this.appStocks = appStocks;
		this.fishingTrips = fishingTrips;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "fishing_activity_id")
	public FishingActivity getFishingActivity() {
		return this.fishingActivity;
	}

	public void setFishingActivity(
			FishingActivity fishingActivity) {
		this.fishingActivity = fishingActivity;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "size_distribution_id", unique = true, nullable = false)
	public SizeDistribution getSizeDistribution() {
		return this.sizeDistribution;
	}

	public void setSizeDistribution(
			SizeDistribution sizeDistribution) {
		this.sizeDistribution = sizeDistribution;
	}

	@Column(name = "type_code", nullable = false)
	public String getTypeCode() {
		return this.typeCode;
	}

	public void setTypeCode(String typeCode) {
		this.typeCode = typeCode;
	}

	@Column(name = "type_code_list_id", nullable = false)
	public String getTypeCodeListId() {
		return this.typeCodeListId;
	}

	public void setTypeCodeListId(String typeCodeListId) {
		this.typeCodeListId = typeCodeListId;
	}

	@Column(name = "species_code", nullable = false)
	public String getSpeciesCode() {
		return this.speciesCode;
	}

	public void setSpeciesCode(String speciesCode) {
		this.speciesCode = speciesCode;
	}

	@Column(name = "species_code_listid", nullable = false)
	public String getSpeciesCodeListid() {
		return this.speciesCodeListid;
	}

	public void setSpeciesCodeListid(String speciesCodeListid) {
		this.speciesCodeListid = speciesCodeListid;
	}

	@Column(name = "unit_quantity")
	public Long getUnitQuantity() {
		return this.unitQuantity;
	}

	public void setUnitQuantity(Long unitQuantity) {
		this.unitQuantity = unitQuantity;
	}

	@Column(name = "weight_measure", precision = 17, scale = 17)
	public Double getWeightMeasure() {
		return this.weightMeasure;
	}

	public void setWeightMeasure(Double weightMeasure) {
		this.weightMeasure = weightMeasure;
	}

	@Column(name = "weight_measure_unit_code")
	public String getWeightMeasureUnitCode() {
		return this.weightMeasureUnitCode;
	}

	public void setWeightMeasureUnitCode(String weightMeasureUnitCode) {
		this.weightMeasureUnitCode = weightMeasureUnitCode;
	}

	@Column(name = "weight_measure_list_id")
	public String getWeightMeasureListId() {
		return this.weightMeasureListId;
	}

	public void setWeightMeasureListId(String weightMeasureListId) {
		this.weightMeasureListId = weightMeasureListId;
	}

	@Column(name = "usage_code")
	public String getUsageCode() {
		return this.usageCode;
	}

	public void setUsageCode(String usageCode) {
		this.usageCode = usageCode;
	}

	@Column(name = "usage_code_list_id")
	public String getUsageCodeListId() {
		return this.usageCodeListId;
	}

	public void setUsageCodeListId(String usageCodeListId) {
		this.usageCodeListId = usageCodeListId;
	}

	@Column(name = "weighing_means_code")
	public String getWeighingMeansCode() {
		return this.weighingMeansCode;
	}

	public void setWeighingMeansCode(String weighingMeansCode) {
		this.weighingMeansCode = weighingMeansCode;
	}

	@Column(name = "weighing_means_code_list_id")
	public String getWeighingMeansCodeListId() {
		return this.weighingMeansCodeListId;
	}

	public void setWeighingMeansCodeListId(String weighingMeansCodeListId) {
		this.weighingMeansCodeListId = weighingMeansCodeListId;
	}

	@Column(name = "aap_stock_type")
	public String getAapStockType() {
		return this.aapStockType;
	}

	public void setAapStockType(String aapStockType) {
		this.aapStockType = aapStockType;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "faCatch")
	public Set<AapProcess> getAapProcesses() {
		return this.aapProcesses;
	}

	public void setAapProcesses(
			Set<AapProcess> aapProcesses) {
		this.aapProcesses = aapProcesses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "faCatch")
	public Set<FishingGear> getFishingGears() {
		return this.fishingGears;
	}

	public void setFishingGears(
			Set<FishingGear> fishingGears) {
		this.fishingGears = fishingGears;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "faCatch")
	public Set<FluxLocation> getFluxLocations() {
		return this.fluxLocations;
	}

	public void setFluxLocations(
			Set<FluxLocation> fluxLocations) {
		this.fluxLocations = fluxLocations;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "faCatch")
	public Set<FluxCharacteristic> getFluxCharacteristics() {
		return this.fluxCharacteristics;
	}

	public void setFluxCharacteristics(
			Set<FluxCharacteristic> fluxCharacteristics) {
		this.fluxCharacteristics = fluxCharacteristics;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "faCatch")
	public Set<AppStock> getAppStocks() {
		return this.appStocks;
	}

	public void setAppStocks(Set<AppStock> appStocks) {
		this.appStocks = appStocks;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "faCatch")
	public Set<FishingTrip> getFishingTrips() {
		return this.fishingTrips;
	}

	public void setFishingTrips(
			Set<FishingTrip> fishingTrips) {
		this.fishingTrips = fishingTrips;
	}

}
