package eu.europa.ec.fisheries.ers.fa.entities;

// Generated 06-May-2016 14:29:53 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * ActivityFaReportDocument generated by hbm2java
 */
@Entity
@Table(name = "activity_fa_report_document", schema = "activity", uniqueConstraints = {
		@UniqueConstraint(columnNames = "flux_report_document_id"),
		@UniqueConstraint(columnNames = "vessel_transport_means_id") })
public class FaReportDocument implements java.io.Serializable {

	private int id;
	private FluxFaReportMessage fluxFaReportMessage;
	private VesselTransportMeans vesselTransportMeans;
	private FluxReportDocument fluxReportDocument;
	private String typeCode;
	private String typeCodeListId;
	private String relatedReport;
	private Date acceptedDatetime;
	private String fmcMarker;
	private String fmcMarkerListId;
	private Set<FaReportIdentifier> faReportIdentifiers = new HashSet<FaReportIdentifier>(
			0);
	private Set<FishingActivity> fishingActivities = new HashSet<FishingActivity>(
			0);

	public FaReportDocument() {
	}

	public FaReportDocument(int id,
			FluxFaReportMessage fluxFaReportMessage,
			VesselTransportMeans vesselTransportMeans,
			FluxReportDocument fluxReportDocument,
			String typeCode, String typeCodeListId) {
		this.id = id;
		this.fluxFaReportMessage = fluxFaReportMessage;
		this.vesselTransportMeans = vesselTransportMeans;
		this.fluxReportDocument = fluxReportDocument;
		this.typeCode = typeCode;
		this.typeCodeListId = typeCodeListId;
	}

	public FaReportDocument(int id,
			FluxFaReportMessage fluxFaReportMessage,
			VesselTransportMeans vesselTransportMeans,
			FluxReportDocument fluxReportDocument,
			String typeCode, String typeCodeListId, String relatedReport,
			Date acceptedDatetime, String fmcMarker, String fmcMarkerListId,
			Set<FaReportIdentifier> faReportIdentifiers,
			Set<FishingActivity> fishingActivities) {
		this.id = id;
		this.fluxFaReportMessage = fluxFaReportMessage;
		this.vesselTransportMeans = vesselTransportMeans;
		this.fluxReportDocument = fluxReportDocument;
		this.typeCode = typeCode;
		this.typeCodeListId = typeCodeListId;
		this.relatedReport = relatedReport;
		this.acceptedDatetime = acceptedDatetime;
		this.fmcMarker = fmcMarker;
		this.fmcMarkerListId = fmcMarkerListId;
		this.faReportIdentifiers = faReportIdentifiers;
		this.fishingActivities = fishingActivities;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "flux_fa_report_message_id", nullable = false)
	public FluxFaReportMessage getFluxFaReportMessage() {
		return this.fluxFaReportMessage;
	}

	public void setFluxFaReportMessage(
			FluxFaReportMessage fluxFaReportMessage) {
		this.fluxFaReportMessage = fluxFaReportMessage;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "vessel_transport_means_id", unique = true, nullable = false)
	public VesselTransportMeans getVesselTransportMeans() {
		return this.vesselTransportMeans;
	}

	public void setVesselTransportMeans(
			VesselTransportMeans vesselTransportMeans) {
		this.vesselTransportMeans = vesselTransportMeans;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "flux_report_document_id", unique = true, nullable = false)
	public FluxReportDocument getFluxReportDocument() {
		return this.fluxReportDocument;
	}

	public void setFluxReportDocument(
			FluxReportDocument fluxReportDocument) {
		this.fluxReportDocument = fluxReportDocument;
	}

	@Column(name = "type_code", nullable = false)
	public String getTypeCode() {
		return this.typeCode;
	}

	public void setTypeCode(String typeCode) {
		this.typeCode = typeCode;
	}

	@Column(name = "type_code_list_id", nullable = false)
	public String getTypeCodeListId() {
		return this.typeCodeListId;
	}

	public void setTypeCodeListId(String typeCodeListId) {
		this.typeCodeListId = typeCodeListId;
	}

	@Column(name = "related_report")
	public String getRelatedReport() {
		return this.relatedReport;
	}

	public void setRelatedReport(String relatedReport) {
		this.relatedReport = relatedReport;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "accepted_datetime", length = 29)
	public Date getAcceptedDatetime() {
		return this.acceptedDatetime;
	}

	public void setAcceptedDatetime(Date acceptedDatetime) {
		this.acceptedDatetime = acceptedDatetime;
	}

	@Column(name = "fmc_marker")
	public String getFmcMarker() {
		return this.fmcMarker;
	}

	public void setFmcMarker(String fmcMarker) {
		this.fmcMarker = fmcMarker;
	}

	@Column(name = "fmc_marker_list_id")
	public String getFmcMarkerListId() {
		return this.fmcMarkerListId;
	}

	public void setFmcMarkerListId(String fmcMarkerListId) {
		this.fmcMarkerListId = fmcMarkerListId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "faReportDocument")
	public Set<FaReportIdentifier> getFaReportIdentifiers() {
		return this.faReportIdentifiers;
	}

	public void setFaReportIdentifiers(
			Set<FaReportIdentifier> faReportIdentifiers) {
		this.faReportIdentifiers = faReportIdentifiers;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "faReportDocument")
	public Set<FishingActivity> getFishingActivities() {
		return this.fishingActivities;
	}

	public void setFishingActivities(
			Set<FishingActivity> fishingActivities) {
		this.fishingActivities = fishingActivities;
	}

}
