package eu.europa.ec.fisheries.ers.fa.entities;

// Generated 06-May-2016 14:29:53 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ActivityFaReportIdentifier generated by hbm2java
 */
@Entity
@Table(name = "activity_fa_report_identifier", schema = "activity")
public class FaReportIdentifier implements java.io.Serializable {

	private int id;
	private FaReportDocument faReportDocument;
	private String faReportIdentifierId;
	private String faReportIdentifierSchemeId;

	public FaReportIdentifier() {
	}

	public FaReportIdentifier(int id) {
		this.id = id;
	}

	public FaReportIdentifier(int id,
			FaReportDocument faReportDocument,
			String faReportIdentifierId, String faReportIdentifierSchemeId) {
		this.id = id;
		this.faReportDocument = faReportDocument;
		this.faReportIdentifierId = faReportIdentifierId;
		this.faReportIdentifierSchemeId = faReportIdentifierSchemeId;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "fa_report_document_id")
	public FaReportDocument getFaReportDocument() {
		return this.faReportDocument;
	}

	public void setFaReportDocument(
			FaReportDocument faReportDocument) {
		this.faReportDocument = faReportDocument;
	}

	@Column(name = "fa_report_identifier_id")
	public String getFaReportIdentifierId() {
		return this.faReportIdentifierId;
	}

	public void setFaReportIdentifierId(String faReportIdentifierId) {
		this.faReportIdentifierId = faReportIdentifierId;
	}

	@Column(name = "fa_report_identifier_scheme_id")
	public String getFaReportIdentifierSchemeId() {
		return this.faReportIdentifierSchemeId;
	}

	public void setFaReportIdentifierSchemeId(String faReportIdentifierSchemeId) {
		this.faReportIdentifierSchemeId = faReportIdentifierSchemeId;
	}

}
