package eu.europa.ec.fisheries.ers.fa.entities;

// Generated 06-May-2016 14:29:53 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ActivityFishingGear generated by hbm2java
 */
@Entity
@Table(name = "activity_fishing_gear", schema = "activity")
public class FishingGear implements java.io.Serializable {

	private int id;
	private GearProblem gearProblem;
	private FaCatch faCatch;
	private FishingActivity fishingActivity;
	private String typeCode;
	private String typeCodeListId;
	private String roleCode;
	private String roleCodeListId;
	private Set<GearCharacteristic> gearCharacteristics = new HashSet<GearCharacteristic>(
			0);

	public FishingGear() {
	}

	public FishingGear(int id, String typeCode, String typeCodeListId,
			String roleCode, String roleCodeListId) {
		this.id = id;
		this.typeCode = typeCode;
		this.typeCodeListId = typeCodeListId;
		this.roleCode = roleCode;
		this.roleCodeListId = roleCodeListId;
	}

	public FishingGear(int id, GearProblem gearProblem,
			FaCatch faCatch,
			FishingActivity fishingActivity, String typeCode,
			String typeCodeListId, String roleCode, String roleCodeListId,
			Set<GearCharacteristic> gearCharacteristics) {
		this.id = id;
		this.gearProblem = gearProblem;
		this.faCatch = faCatch;
		this.fishingActivity = fishingActivity;
		this.typeCode = typeCode;
		this.typeCodeListId = typeCodeListId;
		this.roleCode = roleCode;
		this.roleCodeListId = roleCodeListId;
		this.gearCharacteristics = gearCharacteristics;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "gear_problem_id")
	public GearProblem getGearProblem() {
		return this.gearProblem;
	}

	public void setGearProblem(GearProblem gearProblem) {
		this.gearProblem = gearProblem;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "fa_catch_id")
	public FaCatch getFaCatch() {
		return this.faCatch;
	}

	public void setFaCatch(FaCatch faCatch) {
		this.faCatch = faCatch;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "fishing_activity_id")
	public FishingActivity getFishingActivity() {
		return this.fishingActivity;
	}

	public void setFishingActivity(
			FishingActivity fishingActivity) {
		this.fishingActivity = fishingActivity;
	}

	@Column(name = "type_code", nullable = false)
	public String getTypeCode() {
		return this.typeCode;
	}

	public void setTypeCode(String typeCode) {
		this.typeCode = typeCode;
	}

	@Column(name = "type_code_list_id", nullable = false)
	public String getTypeCodeListId() {
		return this.typeCodeListId;
	}

	public void setTypeCodeListId(String typeCodeListId) {
		this.typeCodeListId = typeCodeListId;
	}

	@Column(name = "role_code", nullable = false)
	public String getRoleCode() {
		return this.roleCode;
	}

	public void setRoleCode(String roleCode) {
		this.roleCode = roleCode;
	}

	@Column(name = "role_code_list_id", nullable = false)
	public String getRoleCodeListId() {
		return this.roleCodeListId;
	}

	public void setRoleCodeListId(String roleCodeListId) {
		this.roleCodeListId = roleCodeListId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "fishingGear")
	public Set<GearCharacteristic> getGearCharacteristics() {
		return this.gearCharacteristics;
	}

	public void setGearCharacteristics(
			Set<GearCharacteristic> gearCharacteristics) {
		this.gearCharacteristics = gearCharacteristics;
	}

}
