package eu.europa.ec.fisheries.ers.fa.entities;

// Generated 06-May-2016 14:29:53 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ActivityFishingTrip generated by hbm2java
 */
@Entity
@Table(name = "activity_fishing_trip", schema = "activity")
public class FishingTrip implements java.io.Serializable {

	private int id;
	private FaCatch faCatch;
	private FishingActivity fishingActivity;
	private String typeCode;
	private String typeCodeListId;
	private Set<DelimitedPeriod> delimitedPeriods = new HashSet<DelimitedPeriod>(
			0);
	private Set<FishingTripIdentifier> fishingTripIdentifiers = new HashSet<FishingTripIdentifier>(
			0);

	public FishingTrip() {
	}

	public FishingTrip(int id) {
		this.id = id;
	}

	public FishingTrip(int id, FaCatch faCatch,
			FishingActivity fishingActivity, String typeCode,
			String typeCodeListId,
			Set<DelimitedPeriod> delimitedPeriods,
			Set<FishingTripIdentifier> fishingTripIdentifiers) {
		this.id = id;
		this.faCatch = faCatch;
		this.fishingActivity = fishingActivity;
		this.typeCode = typeCode;
		this.typeCodeListId = typeCodeListId;
		this.delimitedPeriods = delimitedPeriods;
		this.fishingTripIdentifiers = fishingTripIdentifiers;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "fa_catch_id")
	public FaCatch getFaCatch() {
		return this.faCatch;
	}

	public void setFaCatch(FaCatch faCatch) {
		this.faCatch = faCatch;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "fishing_activity_id")
	public FishingActivity getFishingActivity() {
		return this.fishingActivity;
	}

	public void setFishingActivity(
			FishingActivity fishingActivity) {
		this.fishingActivity = fishingActivity;
	}

	@Column(name = "type_code")
	public String getTypeCode() {
		return this.typeCode;
	}

	public void setTypeCode(String typeCode) {
		this.typeCode = typeCode;
	}

	@Column(name = "type_code_list_id")
	public String getTypeCodeListId() {
		return this.typeCodeListId;
	}

	public void setTypeCodeListId(String typeCodeListId) {
		this.typeCodeListId = typeCodeListId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "fishingTrip")
	public Set<DelimitedPeriod> getDelimitedPeriods() {
		return this.delimitedPeriods;
	}

	public void setDelimitedPeriods(
			Set<DelimitedPeriod> delimitedPeriods) {
		this.delimitedPeriods = delimitedPeriods;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "fishingTrip")
	public Set<FishingTripIdentifier> getFishingTripIdentifiers() {
		return this.fishingTripIdentifiers;
	}

	public void setFishingTripIdentifiers(
			Set<FishingTripIdentifier> fishingTripIdentifiers) {
		this.fishingTripIdentifiers = fishingTripIdentifiers;
	}

}
