package eu.europa.ec.fisheries.ers.fa.entities;

// Generated 06-May-2016 14:29:53 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ActivityFishingActivityIdentifier generated by hbm2java
 */
@Entity
@Table(name = "activity_fishing_activity_identifier", schema = "activity")
public class FishingActivityIdentifier implements java.io.Serializable {

	private int id;
	private FishingActivity fishingActivity;
	private String faIdentifierId;
	private String faIdentifierSchemeId;

	public FishingActivityIdentifier() {
	}

	public FishingActivityIdentifier(int id) {
		this.id = id;
	}

	public FishingActivityIdentifier(int id,
			FishingActivity fishingActivity,
			String faIdentifierId, String faIdentifierSchemeId) {
		this.id = id;
		this.fishingActivity = fishingActivity;
		this.faIdentifierId = faIdentifierId;
		this.faIdentifierSchemeId = faIdentifierSchemeId;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "fishing_activity_id")
	public FishingActivity getFishingActivity() {
		return this.fishingActivity;
	}

	public void setFishingActivity(
			FishingActivity fishingActivity) {
		this.fishingActivity = fishingActivity;
	}

	@Column(name = "fa_identifier_id")
	public String getFaIdentifierId() {
		return this.faIdentifierId;
	}

	public void setFaIdentifierId(String faIdentifierId) {
		this.faIdentifierId = faIdentifierId;
	}

	@Column(name = "fa_identifier_scheme_id")
	public String getFaIdentifierSchemeId() {
		return this.faIdentifierSchemeId;
	}

	public void setFaIdentifierSchemeId(String faIdentifierSchemeId) {
		this.faIdentifierSchemeId = faIdentifierSchemeId;
	}

}
