package eu.europa.ec.fisheries.ers.fa.entities;

// Generated 06-May-2016 14:29:53 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * ActivityFishingActivity generated by hbm2java
 */
@Entity
@Table(name = "activity_fishing_activity", schema = "activity", uniqueConstraints = {
		@UniqueConstraint(columnNames = "source_vessel_char_id"),
		@UniqueConstraint(columnNames = "dest_vessel_char_id") })
public class FishingActivity implements java.io.Serializable {

	private int id;
	private FaReportDocument faReportDocument;
	private VesselStorageCharacteristics vesselStorageCharacteristicsBySourceVesselCharId;
	private VesselStorageCharacteristics vesselStorageCharacteristicsByDestVesselCharId;
	private String typeCode;
	private String typeCodeListid;
	private Date occurence;
	private String reasonCode;
	private String reasonCodeListId;
	private String vesselActivityCode;
	private String vesselActivityCodeListId;
	private String fisheryTypeCode;
	private String fisheryTypeCodeListId;
	private String speciesTargetCode;
	private String speciesTargetCodeListId;
	private Long operationQuantity;
	private Double fishingDurationMeasure;
	private Integer flapDocumentId;
	private String flapDocumentSchemaId;
	private Set<FaCatch> faCatchs = new HashSet<FaCatch>(
			0);
	private Set<DelimitedPeriod> delimitedPeriods = new HashSet<DelimitedPeriod>(
			0);
	private Set<FishingActivityIdentifier> fishingActivityIdentifiers = new HashSet<FishingActivityIdentifier>(
			0);
	private Set<FishingTrip> fishingTrips = new HashSet<FishingTrip>(
			0);
	private Set<FishingGear> fishingGears = new HashSet<FishingGear>(
			0);
	private Set<RelatedFishingActivity> relatedFishingActivities = new HashSet<RelatedFishingActivity>(
			0);
	private Set<FluxCharacteristic> fluxCharacteristics = new HashSet<FluxCharacteristic>(
			0);
	private Set<GearProblem> gearProblems = new HashSet<GearProblem>(
			0);

	public FishingActivity() {
	}

	public FishingActivity(int id, String typeCode,
			String typeCodeListid) {
		this.id = id;
		this.typeCode = typeCode;
		this.typeCodeListid = typeCodeListid;
	}

	public FishingActivity(
			int id,
			FaReportDocument faReportDocument,
			VesselStorageCharacteristics vesselStorageCharacteristicsBySourceVesselCharId,
			VesselStorageCharacteristics vesselStorageCharacteristicsByDestVesselCharId,
			String typeCode,
			String typeCodeListid,
			Date occurence,
			String reasonCode,
			String reasonCodeListId,
			String vesselActivityCode,
			String vesselActivityCodeListId,
			String fisheryTypeCode,
			String fisheryTypeCodeListId,
			String speciesTargetCode,
			String speciesTargetCodeListId,
			Long operationQuantity,
			Double fishingDurationMeasure,
			Integer flapDocumentId,
			String flapDocumentSchemaId,
			Set<FaCatch> faCatchs,
			Set<DelimitedPeriod> delimitedPeriods,
			Set<FishingActivityIdentifier> fishingActivityIdentifiers,
			Set<FishingTrip> fishingTrips,
			Set<FishingGear> fishingGears,
			Set<RelatedFishingActivity> relatedFishingActivities,
			Set<FluxCharacteristic> fluxCharacteristics,
			Set<GearProblem> gearProblems) {
		this.id = id;
		this.faReportDocument = faReportDocument;
		this.vesselStorageCharacteristicsBySourceVesselCharId = vesselStorageCharacteristicsBySourceVesselCharId;
		this.vesselStorageCharacteristicsByDestVesselCharId = vesselStorageCharacteristicsByDestVesselCharId;
		this.typeCode = typeCode;
		this.typeCodeListid = typeCodeListid;
		this.occurence = occurence;
		this.reasonCode = reasonCode;
		this.reasonCodeListId = reasonCodeListId;
		this.vesselActivityCode = vesselActivityCode;
		this.vesselActivityCodeListId = vesselActivityCodeListId;
		this.fisheryTypeCode = fisheryTypeCode;
		this.fisheryTypeCodeListId = fisheryTypeCodeListId;
		this.speciesTargetCode = speciesTargetCode;
		this.speciesTargetCodeListId = speciesTargetCodeListId;
		this.operationQuantity = operationQuantity;
		this.fishingDurationMeasure = fishingDurationMeasure;
		this.flapDocumentId = flapDocumentId;
		this.flapDocumentSchemaId = flapDocumentSchemaId;
		this.faCatchs = faCatchs;
		this.delimitedPeriods = delimitedPeriods;
		this.fishingActivityIdentifiers = fishingActivityIdentifiers;
		this.fishingTrips = fishingTrips;
		this.fishingGears = fishingGears;
		this.relatedFishingActivities = relatedFishingActivities;
		this.fluxCharacteristics = fluxCharacteristics;
		this.gearProblems = gearProblems;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "fa_report_document_id")
	public FaReportDocument getFaReportDocument() {
		return this.faReportDocument;
	}

	public void setFaReportDocument(
			FaReportDocument faReportDocument) {
		this.faReportDocument = faReportDocument;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "source_vessel_char_id", unique = true)
	public VesselStorageCharacteristics getVesselStorageCharacteristicsBySourceVesselCharId() {
		return this.vesselStorageCharacteristicsBySourceVesselCharId;
	}

	public void setVesselStorageCharacteristicsBySourceVesselCharId(
			VesselStorageCharacteristics vesselStorageCharacteristicsBySourceVesselCharId) {
		this.vesselStorageCharacteristicsBySourceVesselCharId = vesselStorageCharacteristicsBySourceVesselCharId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "dest_vessel_char_id", unique = true)
	public VesselStorageCharacteristics getVesselStorageCharacteristicsByDestVesselCharId() {
		return this.vesselStorageCharacteristicsByDestVesselCharId;
	}

	public void setVesselStorageCharacteristicsByDestVesselCharId(
			VesselStorageCharacteristics vesselStorageCharacteristicsByDestVesselCharId) {
		this.vesselStorageCharacteristicsByDestVesselCharId = vesselStorageCharacteristicsByDestVesselCharId;
	}

	@Column(name = "type_code", nullable = false)
	public String getTypeCode() {
		return this.typeCode;
	}

	public void setTypeCode(String typeCode) {
		this.typeCode = typeCode;
	}

	@Column(name = "type_code_listid", nullable = false)
	public String getTypeCodeListid() {
		return this.typeCodeListid;
	}

	public void setTypeCodeListid(String typeCodeListid) {
		this.typeCodeListid = typeCodeListid;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "occurence", length = 29)
	public Date getOccurence() {
		return this.occurence;
	}

	public void setOccurence(Date occurence) {
		this.occurence = occurence;
	}

	@Column(name = "reason_code")
	public String getReasonCode() {
		return this.reasonCode;
	}

	public void setReasonCode(String reasonCode) {
		this.reasonCode = reasonCode;
	}

	@Column(name = "reason_code_list_id")
	public String getReasonCodeListId() {
		return this.reasonCodeListId;
	}

	public void setReasonCodeListId(String reasonCodeListId) {
		this.reasonCodeListId = reasonCodeListId;
	}

	@Column(name = "vessel_activity_code")
	public String getVesselActivityCode() {
		return this.vesselActivityCode;
	}

	public void setVesselActivityCode(String vesselActivityCode) {
		this.vesselActivityCode = vesselActivityCode;
	}

	@Column(name = "vessel_activity_code_list_id")
	public String getVesselActivityCodeListId() {
		return this.vesselActivityCodeListId;
	}

	public void setVesselActivityCodeListId(String vesselActivityCodeListId) {
		this.vesselActivityCodeListId = vesselActivityCodeListId;
	}

	@Column(name = "fishery_type_code")
	public String getFisheryTypeCode() {
		return this.fisheryTypeCode;
	}

	public void setFisheryTypeCode(String fisheryTypeCode) {
		this.fisheryTypeCode = fisheryTypeCode;
	}

	@Column(name = "fishery_type_code_list_id")
	public String getFisheryTypeCodeListId() {
		return this.fisheryTypeCodeListId;
	}

	public void setFisheryTypeCodeListId(String fisheryTypeCodeListId) {
		this.fisheryTypeCodeListId = fisheryTypeCodeListId;
	}

	@Column(name = "species_target_code")
	public String getSpeciesTargetCode() {
		return this.speciesTargetCode;
	}

	public void setSpeciesTargetCode(String speciesTargetCode) {
		this.speciesTargetCode = speciesTargetCode;
	}

	@Column(name = "species_target_code_list_id")
	public String getSpeciesTargetCodeListId() {
		return this.speciesTargetCodeListId;
	}

	public void setSpeciesTargetCodeListId(String speciesTargetCodeListId) {
		this.speciesTargetCodeListId = speciesTargetCodeListId;
	}

	@Column(name = "operation_quantity")
	public Long getOperationQuantity() {
		return this.operationQuantity;
	}

	public void setOperationQuantity(Long operationQuantity) {
		this.operationQuantity = operationQuantity;
	}

	@Column(name = "fishing_duration_measure", precision = 17, scale = 17)
	public Double getFishingDurationMeasure() {
		return this.fishingDurationMeasure;
	}

	public void setFishingDurationMeasure(Double fishingDurationMeasure) {
		this.fishingDurationMeasure = fishingDurationMeasure;
	}

	@Column(name = "flap_document_id")
	public Integer getFlapDocumentId() {
		return this.flapDocumentId;
	}

	public void setFlapDocumentId(Integer flapDocumentId) {
		this.flapDocumentId = flapDocumentId;
	}

	@Column(name = "flap_document_schema_id")
	public String getFlapDocumentSchemaId() {
		return this.flapDocumentSchemaId;
	}

	public void setFlapDocumentSchemaId(String flapDocumentSchemaId) {
		this.flapDocumentSchemaId = flapDocumentSchemaId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "fishingActivity")
	public Set<FaCatch> getFaCatchs() {
		return this.faCatchs;
	}

	public void setFaCatchs(Set<FaCatch> faCatchs) {
		this.faCatchs = faCatchs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "fishingActivity")
	public Set<DelimitedPeriod> getDelimitedPeriods() {
		return this.delimitedPeriods;
	}

	public void setDelimitedPeriods(
			Set<DelimitedPeriod> delimitedPeriods) {
		this.delimitedPeriods = delimitedPeriods;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "fishingActivity")
	public Set<FishingActivityIdentifier> getFishingActivityIdentifiers() {
		return this.fishingActivityIdentifiers;
	}

	public void setFishingActivityIdentifiers(
			Set<FishingActivityIdentifier> fishingActivityIdentifiers) {
		this.fishingActivityIdentifiers = fishingActivityIdentifiers;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "fishingActivity")
	public Set<FishingTrip> getFishingTrips() {
		return this.fishingTrips;
	}

	public void setFishingTrips(
			Set<FishingTrip> fishingTrips) {
		this.fishingTrips = fishingTrips;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "fishingActivity")
	public Set<FishingGear> getFishingGears() {
		return this.fishingGears;
	}

	public void setFishingGears(
			Set<FishingGear> fishingGears) {
		this.fishingGears = fishingGears;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "fishingActivity")
	public Set<RelatedFishingActivity> getRelatedFishingActivities() {
		return this.relatedFishingActivities;
	}

	public void setRelatedFishingActivities(
			Set<RelatedFishingActivity> relatedFishingActivities) {
		this.relatedFishingActivities = relatedFishingActivities;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "fishingActivity")
	public Set<FluxCharacteristic> getFluxCharacteristics() {
		return this.fluxCharacteristics;
	}

	public void setFluxCharacteristics(
			Set<FluxCharacteristic> fluxCharacteristics) {
		this.fluxCharacteristics = fluxCharacteristics;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "fishingActivity")
	public Set<GearProblem> getGearProblems() {
		return this.gearProblems;
	}

	public void setGearProblems(
			Set<GearProblem> gearProblems) {
		this.gearProblems = gearProblems;
	}

}
