package eu.europa.ec.fisheries.ers.fa.entities;
// Generated 06-May-2016 14:29:53 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ActivityFishingTripIdentifier generated by hbm2java
 */
@Entity
@Table(name = "activity_fishing_trip_identifier", schema = "activity")
public class FishingTripIdentifier implements java.io.Serializable {

	private int id;
	private FishingTrip fishingTrip;
	private String tripId;
	private String tripSchemeId;

	public FishingTripIdentifier() {
	}

	public FishingTripIdentifier(int id, String tripId,
			String tripSchemeId) {
		this.id = id;
		this.tripId = tripId;
		this.tripSchemeId = tripSchemeId;
	}

	public FishingTripIdentifier(int id,
			FishingTrip fishingTrip, String tripId,
			String tripSchemeId) {
		this.id = id;
		this.fishingTrip = fishingTrip;
		this.tripId = tripId;
		this.tripSchemeId = tripSchemeId;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "fishing_trip_id")
	public FishingTrip getFishingTrip() {
		return this.fishingTrip;
	}

	public void setFishingTrip(FishingTrip fishingTrip) {
		this.fishingTrip = fishingTrip;
	}

	@Column(name = "trip_id", nullable = false)
	public String getTripId() {
		return this.tripId;
	}

	public void setTripId(String tripId) {
		this.tripId = tripId;
	}

	@Column(name = "trip_scheme_id", nullable = false)
	public String getTripSchemeId() {
		return this.tripSchemeId;
	}

	public void setTripSchemeId(String tripSchemeId) {
		this.tripSchemeId = tripSchemeId;
	}

}
