package eu.europa.ec.fisheries.ers.fa.entities;

// Generated 06-May-2016 14:29:53 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * ActivityFluxLocation generated by hbm2java
 */
@Entity
@Table(name = "activity_flux_location", schema = "activity", uniqueConstraints = @UniqueConstraint(columnNames = "gear_problem_id"))
public class FluxLocation implements java.io.Serializable {

	private int id;
	private GearProblem gearProblem;
	private FaCatch faCatch;
	private Long fishingActivityId;
	private String typeCode;
	private String typeCodeListId;
	private String countryId;
	private String rfmoCode;
	private Double latitude;
	private String fluxLocationType;
	private String countryIdSchemeId;
	private String fluxLocationIdentifier;
	private String fluxLocationIdentifierSchemeId;
	private String geopoliticalRegionCode;
	private String geopoliticalRegionCodeListId;
	private String name;
	private String sovereignRightsCountryCode;
	private String jurisdictionCountryCode;
	private Double altitude;
	private String systemId;
	private Set<FluxCharacteristic> fluxCharacteristics = new HashSet<FluxCharacteristic>(
			0);
	private Set<StructuredAddress> structuredAddresses = new HashSet<StructuredAddress>(
			0);

	public FluxLocation() {
	}

	public FluxLocation(int id, String typeCode, String typeCodeListId,
			String fluxLocationType) {
		this.id = id;
		this.typeCode = typeCode;
		this.typeCodeListId = typeCodeListId;
		this.fluxLocationType = fluxLocationType;
	}

	public FluxLocation(int id,
			GearProblem gearProblem,
			FaCatch faCatch, Long fishingActivityId,
			String typeCode, String typeCodeListId, String countryId,
			String rfmoCode, Double latitude, String fluxLocationType,
			String countryIdSchemeId, String fluxLocationIdentifier,
			String fluxLocationIdentifierSchemeId,
			String geopoliticalRegionCode, String geopoliticalRegionCodeListId,
			String name, String sovereignRightsCountryCode,
			String jurisdictionCountryCode, Double altitude, String systemId,
			Set<FluxCharacteristic> fluxCharacteristics,
			Set<StructuredAddress> structuredAddresses) {
		this.id = id;
		this.gearProblem = gearProblem;
		this.faCatch = faCatch;
		this.fishingActivityId = fishingActivityId;
		this.typeCode = typeCode;
		this.typeCodeListId = typeCodeListId;
		this.countryId = countryId;
		this.rfmoCode = rfmoCode;
		this.latitude = latitude;
		this.fluxLocationType = fluxLocationType;
		this.countryIdSchemeId = countryIdSchemeId;
		this.fluxLocationIdentifier = fluxLocationIdentifier;
		this.fluxLocationIdentifierSchemeId = fluxLocationIdentifierSchemeId;
		this.geopoliticalRegionCode = geopoliticalRegionCode;
		this.geopoliticalRegionCodeListId = geopoliticalRegionCodeListId;
		this.name = name;
		this.sovereignRightsCountryCode = sovereignRightsCountryCode;
		this.jurisdictionCountryCode = jurisdictionCountryCode;
		this.altitude = altitude;
		this.systemId = systemId;
		this.fluxCharacteristics = fluxCharacteristics;
		this.structuredAddresses = structuredAddresses;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "gear_problem_id", unique = true)
	public GearProblem getGearProblem() {
		return this.gearProblem;
	}

	public void setGearProblem(GearProblem gearProblem) {
		this.gearProblem = gearProblem;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "fa_catch_id")
	public FaCatch getFaCatch() {
		return this.faCatch;
	}

	public void setFaCatch(FaCatch faCatch) {
		this.faCatch = faCatch;
	}

	@Column(name = "fishing_activity_id")
	public Long getFishingActivityId() {
		return this.fishingActivityId;
	}

	public void setFishingActivityId(Long fishingActivityId) {
		this.fishingActivityId = fishingActivityId;
	}

	@Column(name = "type_code", nullable = false)
	public String getTypeCode() {
		return this.typeCode;
	}

	public void setTypeCode(String typeCode) {
		this.typeCode = typeCode;
	}

	@Column(name = "type_code_list_id", nullable = false)
	public String getTypeCodeListId() {
		return this.typeCodeListId;
	}

	public void setTypeCodeListId(String typeCodeListId) {
		this.typeCodeListId = typeCodeListId;
	}

	@Column(name = "country_id")
	public String getCountryId() {
		return this.countryId;
	}

	public void setCountryId(String countryId) {
		this.countryId = countryId;
	}

	@Column(name = "rfmo_code")
	public String getRfmoCode() {
		return this.rfmoCode;
	}

	public void setRfmoCode(String rfmoCode) {
		this.rfmoCode = rfmoCode;
	}

	@Column(name = "latitude", precision = 17, scale = 17)
	public Double getLatitude() {
		return this.latitude;
	}

	public void setLatitude(Double latitude) {
		this.latitude = latitude;
	}

	@Column(name = "flux_location_type", nullable = false)
	public String getFluxLocationType() {
		return this.fluxLocationType;
	}

	public void setFluxLocationType(String fluxLocationType) {
		this.fluxLocationType = fluxLocationType;
	}

	@Column(name = "country_id_scheme_id")
	public String getCountryIdSchemeId() {
		return this.countryIdSchemeId;
	}

	public void setCountryIdSchemeId(String countryIdSchemeId) {
		this.countryIdSchemeId = countryIdSchemeId;
	}

	@Column(name = "flux_location_identifier")
	public String getFluxLocationIdentifier() {
		return this.fluxLocationIdentifier;
	}

	public void setFluxLocationIdentifier(String fluxLocationIdentifier) {
		this.fluxLocationIdentifier = fluxLocationIdentifier;
	}

	@Column(name = "flux_location_identifier_scheme_id")
	public String getFluxLocationIdentifierSchemeId() {
		return this.fluxLocationIdentifierSchemeId;
	}

	public void setFluxLocationIdentifierSchemeId(
			String fluxLocationIdentifierSchemeId) {
		this.fluxLocationIdentifierSchemeId = fluxLocationIdentifierSchemeId;
	}

	@Column(name = "geopolitical_region_code")
	public String getGeopoliticalRegionCode() {
		return this.geopoliticalRegionCode;
	}

	public void setGeopoliticalRegionCode(String geopoliticalRegionCode) {
		this.geopoliticalRegionCode = geopoliticalRegionCode;
	}

	@Column(name = "geopolitical_region_code_list_id")
	public String getGeopoliticalRegionCodeListId() {
		return this.geopoliticalRegionCodeListId;
	}

	public void setGeopoliticalRegionCodeListId(
			String geopoliticalRegionCodeListId) {
		this.geopoliticalRegionCodeListId = geopoliticalRegionCodeListId;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "sovereign_rights_country_code")
	public String getSovereignRightsCountryCode() {
		return this.sovereignRightsCountryCode;
	}

	public void setSovereignRightsCountryCode(String sovereignRightsCountryCode) {
		this.sovereignRightsCountryCode = sovereignRightsCountryCode;
	}

	@Column(name = "jurisdiction_country_code")
	public String getJurisdictionCountryCode() {
		return this.jurisdictionCountryCode;
	}

	public void setJurisdictionCountryCode(String jurisdictionCountryCode) {
		this.jurisdictionCountryCode = jurisdictionCountryCode;
	}

	@Column(name = "altitude", precision = 17, scale = 17)
	public Double getAltitude() {
		return this.altitude;
	}

	public void setAltitude(Double altitude) {
		this.altitude = altitude;
	}

	@Column(name = "system_id")
	public String getSystemId() {
		return this.systemId;
	}

	public void setSystemId(String systemId) {
		this.systemId = systemId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "fluxLocation")
	public Set<FluxCharacteristic> getFluxCharacteristics() {
		return this.fluxCharacteristics;
	}

	public void setFluxCharacteristics(
			Set<FluxCharacteristic> fluxCharacteristics) {
		this.fluxCharacteristics = fluxCharacteristics;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "fluxLocation")
	public Set<StructuredAddress> getStructuredAddresses() {
		return this.structuredAddresses;
	}

	public void setStructuredAddresses(
			Set<StructuredAddress> StructuredAddresses) {
		this.structuredAddresses = structuredAddresses;
	}

}
