package eu.europa.ec.fisheries.ers.fa.entities;

// Generated 06-May-2016 14:29:53 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ActivityFluxFaReportMessage generated by hbm2java
 */
@Entity
@Table(name = "activity_flux_fa_report_message", schema = "activity")
public class FluxFaReportMessage implements java.io.Serializable {

	private int id;
	private FluxReportDocument fluxReportDocument;
	private Set<FaReportDocument> faReportDocuments = new HashSet<FaReportDocument>(
			0);

	public FluxFaReportMessage() {
	}

	public FluxFaReportMessage(int id) {
		this.id = id;
	}

	public FluxFaReportMessage(int id,
			FluxReportDocument fluxReportDocument,
			Set<FaReportDocument> faReportDocuments) {
		this.id = id;
		this.fluxReportDocument = fluxReportDocument;
		this.faReportDocuments = faReportDocuments;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "flux_report_document_id")
	public FluxReportDocument getFluxReportDocument() {
		return this.fluxReportDocument;
	}

	public void setFluxReportDocument(
			FluxReportDocument fluxReportDocument) {
		this.fluxReportDocument = fluxReportDocument;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "fluxFaReportMessage")
	public Set<FaReportDocument> getFaReportDocuments() {
		return this.faReportDocuments;
	}

	public void setFaReportDocuments(
			Set<FaReportDocument> faReportDocuments) {
		this.faReportDocuments = faReportDocuments;
	}

}
