package eu.europa.ec.fisheries.ers.fa.entities;

// Generated 06-May-2016 14:29:53 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ActivityGearCharacteristic generated by hbm2java
 */
@Entity
@Table(name = "activity_gear_characteristic", schema = "activity")
public class GearCharacteristic implements java.io.Serializable {

	private int id;
	private FishingGear fishingGear;
	private String typeCode;
	private String typeCodeListId;
	private String description;
	private Double valueMeasure;
	private Date valueDateTime;
	private String valueIndicator;
	private String valueCode;
	private String valueText;
	private Double valueQuantity;

	public GearCharacteristic() {
	}

	public GearCharacteristic(int id, String typeCode,
			String typeCodeListId) {
		this.id = id;
		this.typeCode = typeCode;
		this.typeCodeListId = typeCodeListId;
	}

	public GearCharacteristic(int id,
			FishingGear fishingGear, String typeCode,
			String typeCodeListId, String description, Double valueMeasure,
			Date valueDateTime, String valueIndicator, String valueCode,
			String valueText, Double valueQuantity) {
		this.id = id;
		this.fishingGear = fishingGear;
		this.typeCode = typeCode;
		this.typeCodeListId = typeCodeListId;
		this.description = description;
		this.valueMeasure = valueMeasure;
		this.valueDateTime = valueDateTime;
		this.valueIndicator = valueIndicator;
		this.valueCode = valueCode;
		this.valueText = valueText;
		this.valueQuantity = valueQuantity;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "fishing_gear_id")
	public FishingGear getFishingGear() {
		return this.fishingGear;
	}

	public void setFishingGear(FishingGear fishingGear) {
		this.fishingGear = fishingGear;
	}

	@Column(name = "type_code", nullable = false)
	public String getTypeCode() {
		return this.typeCode;
	}

	public void setTypeCode(String typeCode) {
		this.typeCode = typeCode;
	}

	@Column(name = "type_code_list_id", nullable = false)
	public String getTypeCodeListId() {
		return this.typeCodeListId;
	}

	public void setTypeCodeListId(String typeCodeListId) {
		this.typeCodeListId = typeCodeListId;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "value_measure", precision = 17, scale = 17)
	public Double getValueMeasure() {
		return this.valueMeasure;
	}

	public void setValueMeasure(Double valueMeasure) {
		this.valueMeasure = valueMeasure;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "value_date_time", length = 29)
	public Date getValueDateTime() {
		return this.valueDateTime;
	}

	public void setValueDateTime(Date valueDateTime) {
		this.valueDateTime = valueDateTime;
	}

	@Column(name = "value_indicator")
	public String getValueIndicator() {
		return this.valueIndicator;
	}

	public void setValueIndicator(String valueIndicator) {
		this.valueIndicator = valueIndicator;
	}

	@Column(name = "value_code")
	public String getValueCode() {
		return this.valueCode;
	}

	public void setValueCode(String valueCode) {
		this.valueCode = valueCode;
	}

	@Column(name = "value_text")
	public String getValueText() {
		return this.valueText;
	}

	public void setValueText(String valueText) {
		this.valueText = valueText;
	}

	@Column(name = "value_quantity", precision = 17, scale = 17)
	public Double getValueQuantity() {
		return this.valueQuantity;
	}

	public void setValueQuantity(Double valueQuantity) {
		this.valueQuantity = valueQuantity;
	}

}
