package eu.europa.ec.fisheries.ers.fa.entities;

// Generated 06-May-2016 14:29:53 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ActivityGearProblem generated by hbm2java
 */
@Entity
@Table(name = "activity_gear_problem", schema = "activity")
public class GearProblem implements java.io.Serializable {

	private int id;
	private FishingActivity fishingActivity;
	private String typeCode;
	private String typeCodeListId;
	private int affectedQuantity;
	private String recoveryMeasureCode;
	private String recoveryMeasureCodeListId;
	private Set<FluxLocation> fluxLocations = new HashSet<FluxLocation>(
			0);
	private Set<FishingGear> fishingGears = new HashSet<FishingGear>(
			0);

	public GearProblem() {
	}

	public GearProblem(int id, String typeCode, String typeCodeListId,
			int affectedQuantity, String recoveryMeasureCode,
			String recoveryMeasureCodeListId) {
		this.id = id;
		this.typeCode = typeCode;
		this.typeCodeListId = typeCodeListId;
		this.affectedQuantity = affectedQuantity;
		this.recoveryMeasureCode = recoveryMeasureCode;
		this.recoveryMeasureCodeListId = recoveryMeasureCodeListId;
	}

	public GearProblem(int id,
			FishingActivity fishingActivity, String typeCode,
			String typeCodeListId, int affectedQuantity,
			String recoveryMeasureCode, String recoveryMeasureCodeListId,
			Set<FluxLocation> fluxLocations,
			Set<FishingGear> FishingGears) {
		this.id = id;
		this.fishingActivity = fishingActivity;
		this.typeCode = typeCode;
		this.typeCodeListId = typeCodeListId;
		this.affectedQuantity = affectedQuantity;
		this.recoveryMeasureCode = recoveryMeasureCode;
		this.recoveryMeasureCodeListId = recoveryMeasureCodeListId;
		this.fluxLocations = fluxLocations;
		this.fishingGears = fishingGears;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "fishing_activity_id")
	public FishingActivity getFishingActivity() {
		return this.fishingActivity;
	}

	public void setFishingActivity(
			FishingActivity fishingActivity) {
		this.fishingActivity = fishingActivity;
	}

	@Column(name = "type_code", nullable = false)
	public String getTypeCode() {
		return this.typeCode;
	}

	public void setTypeCode(String typeCode) {
		this.typeCode = typeCode;
	}

	@Column(name = "type_code_list_id", nullable = false)
	public String getTypeCodeListId() {
		return this.typeCodeListId;
	}

	public void setTypeCodeListId(String typeCodeListId) {
		this.typeCodeListId = typeCodeListId;
	}

	@Column(name = "affected_quantity", nullable = false)
	public int getAffectedQuantity() {
		return this.affectedQuantity;
	}

	public void setAffectedQuantity(int affectedQuantity) {
		this.affectedQuantity = affectedQuantity;
	}

	@Column(name = "recovery_measure_code", nullable = false)
	public String getRecoveryMeasureCode() {
		return this.recoveryMeasureCode;
	}

	public void setRecoveryMeasureCode(String recoveryMeasureCode) {
		this.recoveryMeasureCode = recoveryMeasureCode;
	}

	@Column(name = "recovery_measure_code_list_id", nullable = false)
	public String getRecoveryMeasureCodeListId() {
		return this.recoveryMeasureCodeListId;
	}

	public void setRecoveryMeasureCodeListId(String recoveryMeasureCodeListId) {
		this.recoveryMeasureCodeListId = recoveryMeasureCodeListId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "gearProblem")
	public Set<FluxLocation> getFluxLocations() {
		return this.fluxLocations;
	}

	public void setFluxLocations(
			Set<FluxLocation> fluxLocations) {
		this.fluxLocations = fluxLocations;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "gearProblem")
	public Set<FishingGear> getFishingGears() {
		return this.fishingGears;
	}

	public void setFishingGears(
			Set<FishingGear> fishingGears) {
		this.fishingGears = fishingGears;
	}

}
