package eu.europa.ec.fisheries.ers.fa.entities;

// Generated 06-May-2016 14:29:53 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ActivityRegistrationLocation generated by hbm2java
 */
@Entity
@Table(name = "activity_registration_location", schema = "activity")
public class RegistrationLocation implements java.io.Serializable {

	private int id;
	private String countryId;
	private String description;
	private String regionCode;
	private String regionCodeListId;
	private String registrationLocationId;
	private String name;
	private String typeCode;
	private String typeCodeListId;
	private Set<RegistrationEvent> registrationEvents = new HashSet<RegistrationEvent>(
			0);

	public RegistrationLocation() {
	}

	public RegistrationLocation(int id) {
		this.id = id;
	}

	public RegistrationLocation(int id, String countryId,
			String description, String regionCode, String regionCodeListId,
			String registrationLocationId, String name, String typeCode,
			String typeCodeListId,
			Set<RegistrationEvent> registrationEvents) {
		this.id = id;
		this.countryId = countryId;
		this.description = description;
		this.regionCode = regionCode;
		this.regionCodeListId = regionCodeListId;
		this.registrationLocationId = registrationLocationId;
		this.name = name;
		this.typeCode = typeCode;
		this.typeCodeListId = typeCodeListId;
		this.registrationEvents = registrationEvents;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "country_id")
	public String getCountryId() {
		return this.countryId;
	}

	public void setCountryId(String countryId) {
		this.countryId = countryId;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "region_code")
	public String getRegionCode() {
		return this.regionCode;
	}

	public void setRegionCode(String regionCode) {
		this.regionCode = regionCode;
	}

	@Column(name = "region_code_list_id")
	public String getRegionCodeListId() {
		return this.regionCodeListId;
	}

	public void setRegionCodeListId(String regionCodeListId) {
		this.regionCodeListId = regionCodeListId;
	}

	@Column(name = "registration_location_id")
	public String getRegistrationLocationId() {
		return this.registrationLocationId;
	}

	public void setRegistrationLocationId(String registrationLocationId) {
		this.registrationLocationId = registrationLocationId;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "type_code")
	public String getTypeCode() {
		return this.typeCode;
	}

	public void setTypeCode(String typeCode) {
		this.typeCode = typeCode;
	}

	@Column(name = "type_code_list_id")
	public String getTypeCodeListId() {
		return this.typeCodeListId;
	}

	public void setTypeCodeListId(String typeCodeListId) {
		this.typeCodeListId = typeCodeListId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "registrationLocation")
	public Set<RegistrationEvent> getRegistrationEvents() {
		return this.registrationEvents;
	}

	public void setRegistrationEvents(
			Set<RegistrationEvent> registrationEvents) {
		this.registrationEvents = registrationEvents;
	}

}
