package eu.europa.ec.fisheries.ers.fa.entities;
// Generated 06-May-2016 14:29:53 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ActivityRelatedFishingActivity generated by hbm2java
 */
@Entity
@Table(name = "activity_related_fishing_activity", schema = "activity")
public class RelatedFishingActivity implements java.io.Serializable {

	private int id;
	private FishingActivity fishingActivity;

	public RelatedFishingActivity() {
	}

	public RelatedFishingActivity(int id) {
		this.id = id;
	}

	public RelatedFishingActivity(int id,
			FishingActivity fishingActivity) {
		this.id = id;
		this.fishingActivity = fishingActivity;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "fishing_activity_id")
	public FishingActivity getFishingActivity() {
		return this.fishingActivity;
	}

	public void setFishingActivity(
			FishingActivity fishingActivity) {
		this.fishingActivity = fishingActivity;
	}

}
