package eu.europa.ec.fisheries.ers.fa.entities;

// Generated 06-May-2016 14:29:53 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ActivitySizeDistribution generated by hbm2java
 */
@Entity
@Table(name = "activity_size_distribution", schema = "activity")
public class SizeDistribution implements java.io.Serializable {

	private int id;
	private String classCode;
	private String classCodeListId;
	private String categoryCode;
	private String categoryCodeListId;
	private Set<FaCatch> faCatchs = new HashSet<FaCatch>(
			0);

	public SizeDistribution() {
	}

	public SizeDistribution(int id, String classCode,
			String classCodeListId) {
		this.id = id;
		this.classCode = classCode;
		this.classCodeListId = classCodeListId;
	}

	public SizeDistribution(int id, String classCode,
			String classCodeListId, String categoryCode,
			String categoryCodeListId, Set<FaCatch> FaCatchs) {
		this.id = id;
		this.classCode = classCode;
		this.classCodeListId = classCodeListId;
		this.categoryCode = categoryCode;
		this.categoryCodeListId = categoryCodeListId;
		this.faCatchs = faCatchs;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "class_code", nullable = false)
	public String getClassCode() {
		return this.classCode;
	}

	public void setClassCode(String classCode) {
		this.classCode = classCode;
	}

	@Column(name = "class_code_list_id", nullable = false)
	public String getClassCodeListId() {
		return this.classCodeListId;
	}

	public void setClassCodeListId(String classCodeListId) {
		this.classCodeListId = classCodeListId;
	}

	@Column(name = "category_code")
	public String getCategoryCode() {
		return this.categoryCode;
	}

	public void setCategoryCode(String categoryCode) {
		this.categoryCode = categoryCode;
	}

	@Column(name = "category_code_list_id")
	public String getCategoryCodeListId() {
		return this.categoryCodeListId;
	}

	public void setCategoryCodeListId(String categoryCodeListId) {
		this.categoryCodeListId = categoryCodeListId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sizeDistribution")
	public Set<FaCatch> getFaCatchs() {
		return this.faCatchs;
	}

	public void setFaCatchs(Set<FaCatch> faCatchs) {
		this.faCatchs = faCatchs;
	}

}
