package eu.europa.ec.fisheries.ers.fa.entities;

// Generated 06-May-2016 14:29:53 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ActivityStructuredAddress generated by hbm2java
 */
@Entity
@Table(name = "activity_structured_address", schema = "activity")
public class StructuredAddress implements java.io.Serializable {

	private int id;
	private ContactParty contactParty;
	private FluxLocation fluxLocation;
	private String blockName;
	private String buildingName;
	private String cityName;
	private String citySubdivisionName;
	private int countryCharacter;
	private String countryName;
	private String countrySubdivisionName;
	private String addressId;
	private String plotId;
	private String postOfficeBox;
	private String postcode;
	private String streetname;

	public StructuredAddress() {
	}

	public StructuredAddress(int id, String cityName,
			int countryCharacter, String postcode) {
		this.id = id;
		this.cityName = cityName;
		this.countryCharacter = countryCharacter;
		this.postcode = postcode;
	}

	public StructuredAddress(int id,
			ContactParty contactParty,
			FluxLocation fluxLocation, String blockName,
			String buildingName, String cityName, String citySubdivisionName,
			int countryCharacter, String countryName,
			String countrySubdivisionName, String addressId, String plotId,
			String postOfficeBox, String postcode, String streetname) {
		this.id = id;
		this.contactParty = contactParty;
		this.fluxLocation = fluxLocation;
		this.blockName = blockName;
		this.buildingName = buildingName;
		this.cityName = cityName;
		this.citySubdivisionName = citySubdivisionName;
		this.countryCharacter = countryCharacter;
		this.countryName = countryName;
		this.countrySubdivisionName = countrySubdivisionName;
		this.addressId = addressId;
		this.plotId = plotId;
		this.postOfficeBox = postOfficeBox;
		this.postcode = postcode;
		this.streetname = streetname;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "contact_party_id")
	public ContactParty getContactParty() {
		return this.contactParty;
	}

	public void setContactParty(
			ContactParty contactParty) {
		this.contactParty = contactParty;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "flux_location_id")
	public FluxLocation getFluxLocation() {
		return this.fluxLocation;
	}

	public void setFluxLocation(
			FluxLocation fluxLocation) {
		this.fluxLocation = fluxLocation;
	}

	@Column(name = "block_name", length = 1000)
	public String getBlockName() {
		return this.blockName;
	}

	public void setBlockName(String blockName) {
		this.blockName = blockName;
	}

	@Column(name = "building_name", length = 1000)
	public String getBuildingName() {
		return this.buildingName;
	}

	public void setBuildingName(String buildingName) {
		this.buildingName = buildingName;
	}

	@Column(name = "city_name", nullable = false)
	public String getCityName() {
		return this.cityName;
	}

	public void setCityName(String cityName) {
		this.cityName = cityName;
	}

	@Column(name = "city_subdivision_name")
	public String getCitySubdivisionName() {
		return this.citySubdivisionName;
	}

	public void setCitySubdivisionName(String citySubdivisionName) {
		this.citySubdivisionName = citySubdivisionName;
	}

	@Column(name = "country_character", nullable = false)
	public int getCountryCharacter() {
		return this.countryCharacter;
	}

	public void setCountryCharacter(int countryCharacter) {
		this.countryCharacter = countryCharacter;
	}

	@Column(name = "country_name")
	public String getCountryName() {
		return this.countryName;
	}

	public void setCountryName(String countryName) {
		this.countryName = countryName;
	}

	@Column(name = "country_subdivision_name")
	public String getCountrySubdivisionName() {
		return this.countrySubdivisionName;
	}

	public void setCountrySubdivisionName(String countrySubdivisionName) {
		this.countrySubdivisionName = countrySubdivisionName;
	}

	@Column(name = "address_id")
	public String getAddressId() {
		return this.addressId;
	}

	public void setAddressId(String addressId) {
		this.addressId = addressId;
	}

	@Column(name = "plot_id", length = 1000)
	public String getPlotId() {
		return this.plotId;
	}

	public void setPlotId(String plotId) {
		this.plotId = plotId;
	}

	@Column(name = "post_office_box")
	public String getPostOfficeBox() {
		return this.postOfficeBox;
	}

	public void setPostOfficeBox(String postOfficeBox) {
		this.postOfficeBox = postOfficeBox;
	}

	@Column(name = "postcode", nullable = false)
	public String getPostcode() {
		return this.postcode;
	}

	public void setPostcode(String postcode) {
		this.postcode = postcode;
	}

	@Column(name = "streetname", length = 1000)
	public String getStreetname() {
		return this.streetname;
	}

	public void setStreetname(String streetname) {
		this.streetname = streetname;
	}

}
