package eu.europa.ec.fisheries.ers.fa.entities;

// Generated 06-May-2016 14:29:53 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ActivityVesselStorageCharacteristics generated by hbm2java
 */
@Entity
@Table(name = "activity_vessel_storage_characteristics", schema = "activity")
public class VesselStorageCharacteristics implements
		java.io.Serializable {

	private int id;
	private String vesselId;
	private String vesselSchemaId;
	private String vesselTypeCode;
	private String vesselTypeCodeListId;
	private Set<FishingActivity> fishingActivitiesForDestVesselCharId = new HashSet<FishingActivity>(
			0);
	private Set<FishingActivity> fishingActivitiesForSourceVesselCharId = new HashSet<FishingActivity>(
			0);

	public VesselStorageCharacteristics() {
	}

	public VesselStorageCharacteristics(int id) {
		this.id = id;
	}

	public VesselStorageCharacteristics(
			int id,
			String vesselId,
			String vesselSchemaId,
			String vesselTypeCode,
			String vesselTypeCodeListId,
			Set<FishingActivity> fishingActivitiesForDestVesselCharId,
			Set<FishingActivity> fishingActivitiesForSourceVesselCharId) {
		this.id = id;
		this.vesselId = vesselId;
		this.vesselSchemaId = vesselSchemaId;
		this.vesselTypeCode = vesselTypeCode;
		this.vesselTypeCodeListId = vesselTypeCodeListId;
		this.fishingActivitiesForDestVesselCharId = fishingActivitiesForDestVesselCharId;
		this.fishingActivitiesForSourceVesselCharId = fishingActivitiesForSourceVesselCharId;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "vessel_id")
	public String getVesselId() {
		return this.vesselId;
	}

	public void setVesselId(String vesselId) {
		this.vesselId = vesselId;
	}

	@Column(name = "vessel_schema_id")
	public String getVesselSchemaId() {
		return this.vesselSchemaId;
	}

	public void setVesselSchemaId(String vesselSchemaId) {
		this.vesselSchemaId = vesselSchemaId;
	}

	@Column(name = "vessel_type_code")
	public String getVesselTypeCode() {
		return this.vesselTypeCode;
	}

	public void setVesselTypeCode(String vesselTypeCode) {
		this.vesselTypeCode = vesselTypeCode;
	}

	@Column(name = "vessel_type_code_list_id")
	public String getVesselTypeCodeListId() {
		return this.vesselTypeCodeListId;
	}

	public void setVesselTypeCodeListId(String vesselTypeCodeListId) {
		this.vesselTypeCodeListId = vesselTypeCodeListId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "vesselStorageCharacteristicsByDestVesselCharId")
	public Set<FishingActivity> getFishingActivitiesForDestVesselCharId() {
		return this.fishingActivitiesForDestVesselCharId;
	}

	public void setFishingActivitiesForDestVesselCharId(
			Set<FishingActivity> fishingActivitiesForDestVesselCharId) {
		this.fishingActivitiesForDestVesselCharId = fishingActivitiesForDestVesselCharId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "vesselStorageCharacteristicsBySourceVesselCharId")
	public Set<FishingActivity> getFishingActivitiesForSourceVesselCharId() {
		return this.fishingActivitiesForSourceVesselCharId;
	}

	public void setFishingActivitiesForSourceVesselCharId(
			Set<FishingActivity> fishingActivitiesForSourceVesselCharId) {
		this.fishingActivitiesForSourceVesselCharId = fishingActivitiesForSourceVesselCharId;
	}

}
