package eu.europa.ec.fisheries.ers.fa.entities;
// Generated 06-May-2016 14:29:53 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ActivityVesselCountry generated by hbm2java
 */
@Entity
@Table(name = "activity_vessel_country", schema = "activity")
public class VesselCountry implements java.io.Serializable {

	private int id;
	private VesselTransportMeans vesselTransportMeans;
	private String vesselCountryId;
	private String vesselCountrySchemeId;

	public VesselCountry() {
	}

	public VesselCountry(int id, String vesselCountryId,
			String vesselCountrySchemeId) {
		this.id = id;
		this.vesselCountryId = vesselCountryId;
		this.vesselCountrySchemeId = vesselCountrySchemeId;
	}

	public VesselCountry(int id,
			VesselTransportMeans vesselTransportMeans,
			String vesselCountryId, String vesselCountrySchemeId) {
		this.id = id;
		this.vesselTransportMeans = vesselTransportMeans;
		this.vesselCountryId = vesselCountryId;
		this.vesselCountrySchemeId = vesselCountrySchemeId;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "vessel_transport_means_id")
	public VesselTransportMeans getVesselTransportMeans() {
		return this.vesselTransportMeans;
	}

	public void setVesselTransportMeans(
			VesselTransportMeans vesselTransportMeans) {
		this.vesselTransportMeans = vesselTransportMeans;
	}

	@Column(name = "vessel_country_id", nullable = false)
	public String getVesselCountryId() {
		return this.vesselCountryId;
	}

	public void setVesselCountryId(String vesselCountryId) {
		this.vesselCountryId = vesselCountryId;
	}

	@Column(name = "vessel_country_scheme_id", nullable = false)
	public String getVesselCountrySchemeId() {
		return this.vesselCountrySchemeId;
	}

	public void setVesselCountrySchemeId(String vesselCountrySchemeId) {
		this.vesselCountrySchemeId = vesselCountrySchemeId;
	}

}
