package eu.europa.ec.fisheries.ers.fa.entities;
// Generated 06-May-2016 14:29:53 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ActivityVesselIdentifier generated by hbm2java
 */
@Entity
@Table(name = "activity_vessel_identifier", schema = "activity")
public class VesselIdentifier implements java.io.Serializable {

	private int id;
	private VesselTransportMeans vesselTransportMeans;
	private String vesselIdentifierId;
	private String vesselIdentifierSchemeId;

	public VesselIdentifier() {
	}

	public VesselIdentifier(int id) {
		this.id = id;
	}

	public VesselIdentifier(int id,
			VesselTransportMeans vesselTransportMeans,
			String vesselIdentifierId, String vesselIdentifierSchemeId) {
		this.id = id;
		this.vesselTransportMeans = vesselTransportMeans;
		this.vesselIdentifierId = vesselIdentifierId;
		this.vesselIdentifierSchemeId = vesselIdentifierSchemeId;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "vessel_transport_mean_id")
	public VesselTransportMeans getVesselTransportMeans() {
		return this.vesselTransportMeans;
	}

	public void setVesselTransportMeans(
			VesselTransportMeans vesselTransportMeans) {
		this.vesselTransportMeans = vesselTransportMeans;
	}

	@Column(name = "vessel_identifier_id")
	public String getVesselIdentifierId() {
		return this.vesselIdentifierId;
	}

	public void setVesselIdentifierId(String vesselIdentifierId) {
		this.vesselIdentifierId = vesselIdentifierId;
	}

	@Column(name = "vessel_identifier_scheme_id")
	public String getVesselIdentifierSchemeId() {
		return this.vesselIdentifierSchemeId;
	}

	public void setVesselIdentifierSchemeId(String vesselIdentifierSchemeId) {
		this.vesselIdentifierSchemeId = vesselIdentifierSchemeId;
	}

}
