package eu.europa.ec.fisheries.ers.fa.utils;

/**
 * Created by sanera on 21/03/2017.
 */
public enum FishingActivityTypeEnum {
    DEPARTURE,ARRIVAL,AREA_ENTRY,AREA_EXIT,FISHING_OPERATION,LANDING,TRANSHIPMENT,RELOCATION,GEAR_SHOT,GEAR_RETRIEVAL,START_FISHING,JOINED_FISHING_OPERATION,START_ACTIVITY;
}
